name: Python CI

on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run pipeline
      env:
        DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      run: |
        echo "Secret fetched successfully"
        dvc repro

    - name: Load Model
      run: |
        python src/scripts/load_model.py

    - name: Dagshub Setup and dvc Push
      env:
        access_key_id: ${{ secrets.access_key_id }}
        secret_access_key: ${{ secrets.secret_access_key }}
      run:
        dvc push -r origin
        
    - name: Git Commit and Push (Bot User)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provided token for commit
      run: |
        # Set git configuration to use bot identity for commit
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Commit changes to DVC files and push to the repository
        git add .
        git commit -m "Automated DVC push and updates"
        git push origin main
